---
version: "2.0"

endpoints: 
  nodeip2:
    kind: ip

services:
  codex:
    image: codexstorage/nim-codex:0.2.0
    expose:
    - port: 8070
      as: 8070
      proto: tcp
      to:
        - global: true
          ip: nodeip2
    - port: 8090
      as: 8090
      proto: udp
      to:
        - global: true
          ip: nodeip2
    - port: 8080
      as: 8080
      to:
        - service: nginx
    env:
      - DATA_DIR=/codex/data
      - ETH_PRIVATE_KEY=   # Wallet private key to be used to purchase storage from Codex Marketplace
      - PUBLIC_IP=
 #     - CODEX_LOG_LEVEL=debug
 #     - CODEX_BLOCK_TTL=30d
    command:
    - sh
    - -c
    args:
    - curl -s https://raw.githubusercontent.com/akash-network/awesome-akash/master/codex/codex-main.sh | bash
    params:
      storage:
        codex:
          mount: /codex
          readOnly: false
  codexapp:
    image: codexstorage/codex-marketplace-ui:sha-4b2e179
    expose:
    - port: 80
      as: 80
      to:
        - service: nginx
  nginx:
    image: nginx:1.27
    expose:
      - port: 80
        as: 80
        to:
          - global: true
            ip: nodeip2
        http_options:
          max_body_size: 1073741824
          read_timeout: 500000
          send_timeout: 510000
      - port: 443
        as: 443
        to:
          - global: true
            ip: nodeip2
    env:
      - BASIC_AUTH_USER=codex
      - BASIC_AUTH_PASS=passsecret #CHANGE THIS!!!
      - DOMAIN=         # DNS A record pointing to the PUBLIC_IP defined above, it is needed to get Let's Encrypt certificates to secure your communication with the Codex App and the API
    command:
      - sh
      - -c
    args:
      - curl -s https://raw.githubusercontent.com/akash-network/awesome-akash/master/codex/nginx-main.sh | bash
 
profiles:
  compute:
    codex:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 1Gi
          - size: 10Gi
            name: codex
            attributes:
              persistent: true
              class: beta3
    nginx:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 200Mi
    codexapp:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 200Mi

    
  placement:
    dcloud:
      pricing:
        codex:
          denom: uact
          amount: 100000
        codexapp:
          denom: uact
          amount: 100000
        nginx:
          denom: uact
          amount: 100000

deployment:
  codex:
    dcloud:
      profile: codex
      count: 1 
  codexapp:
    dcloud:
      profile: nginx
      count: 1
  nginx:
    dcloud:
      profile: codexapp
      count: 1

